name: quiz_apps

packages:
  - packages/*
  - apps/*

scripts:
  build-fg-ios: cd apps/four_gospels && derry build ios
  build-fg-android: cd apps/four_gospels && derry build android
  build-fg-ar: cd apps/four_gospels && derry auto_route
