name: quiz_core
description: Quiz Core
version: 0.0.2+11
publish_to: https://onepub.dev/api/kxhbxpsdav/
repository: https://github.com/JakeHadley/quiz_apps

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  advanced_in_app_review: ^1.2.1
  badges: ^3.1.1
  bloc: ^8.0.3
  carousel_slider: ^5.0.0
  cloud_firestore: ^4.3.1
  cloud_functions: ^4.3.3
  connectivity_plus: ^6.0.5
  device_info_plus: ^10.1.2
  equatable: ^2.0.3
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.0.1
  flutter_email_sender: ^6.0.1
  meta: ^1.8.0
  numberpicker: ^2.1.2
  path_provider: ^2.1.1
  random_string: ^2.3.1
  screenshot: ^3.0.0
  share_plus: ^10.0.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^6.0.0
