// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      // ignore: no_default_cases
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJPxZQZiKwvuI1H9FAjGiK8fNhleBGMns',
    appId: '1:449612563741:web:9d9ba38d013f9d40918df4',
    messagingSenderId: '449612563741',
    projectId: 'four-gospels-exigent',
    authDomain: 'four-gospels-exigent.firebaseapp.com',
    storageBucket: 'four-gospels-exigent.appspot.com',
    measurementId: 'G-0E3GMZXSTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOktwR-KkNt2J7sSWXfb_hrdl2GYHJJrU',
    appId: '1:449612563741:android:7e77068ca86e47b7918df4',
    messagingSenderId: '449612563741',
    projectId: 'four-gospels-exigent',
    storageBucket: 'four-gospels-exigent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyhyInZd574OnCs11OQ_n2ge_hGTgRLLE',
    appId: '1:449612563741:ios:40c434e03306f7bd918df4',
    messagingSenderId: '449612563741',
    projectId: 'four-gospels-exigent',
    storageBucket: 'four-gospels-exigent.appspot.com',
    iosClientId:
        '449612563741-kn5mtvtsp2fd2i93rss5l5o8ccblr9nm.apps.googleusercontent.com',
    iosBundleId: 'app.exigentdev.four-gospels',
  );
}
