name: quiz_core
description: Quiz Core
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  badges: ^3.1.1
  bloc: ^8.0.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.3.1
  cloud_functions: ^4.3.3
  connectivity_plus: ^4.0.2
  device_info_plus: ^9.0.3
  equatable: ^2.0.3
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_bloc: ^8.0.1
  flutter_email_sender: ^6.0.1
  meta: ^1.8.0
  numberpicker: ^2.1.2
  path_provider: ^2.1.1
  random_string: ^2.3.1
  screenshot: ^2.1.0
  share_plus: ^7.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
