name: Build Quiz Core

on:
  push:
  pull_request:
  workflow_call:

jobs:
  build-core:
    name: Build Quiz Core
    defaults:
      run:
        working-directory: packages/quiz_core
    runs-on: ubuntu-latest
    steps:
      - name: Common Steps
        uses: ./.github/actions/common_steps.yaml
        with:
          flutter_version: '3.13.8'
          flutter_channel: 'stable'
          cache_key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
          analyze_directories: 'lib test'
          working_directory: packages/quiz_core
          package_get_excludes: "!*"
          concurrency: 4
          test_recursion: false
          test_optimization: false
          coverage_excludes: ''
