name: Publish Quiz Apps

on: 
  push:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
            flutter-version: '3.22.0'
        
        - name: Set up onepub
          run: |
            flutter pub global activate onepub
            export ONEPUB_TOKEN="${{ secrets.ONEPUB_T }}"; onepub import
        - name: Dry run publish to onepub
          id: dryrun
          run: | 
            dart pub publish -n
        - name: Publish to onepub
          if: steps.dryrun.outcome == 'success'
          run: | 
            dart pub publish -f
