name: Semantic PR

on:
  push:
  pull_request:
  workflow_call:

jobs:
  semantic-pull-request:
    name: Semantic PR
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1
