name: four_gospels
description: Four Gospels App
version: 0.0.1+10
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auto_route: ^7.1.0
  badges: ^3.1.1
  bloc: ^8.0.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.3.1
  cloud_functions: ^4.3.3
  device_info_plus: ^9.0.3
  equatable: ^2.0.3
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.11
  flag: ^7.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_animation_progress_bar: ^2.2.1
  flutter_bloc: ^8.0.1
  flutter_email_sender: ^6.0.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.1
  intl: ^0.18.0
  meta: ^1.8.0
  numberpicker: ^2.1.2
  path_provider: ^2.1.1
  quiz_core: ^0.0.1
  screenshot: ^2.1.0
  shared_preferences: ^2.0.15

dev_dependencies:
  auto_route_generator: ^7.0.0
  bloc_test: ^9.0.3
  build_runner:
  flutter_native_splash: ^2.2.15
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter_native_splash:
  color: "#003b77"
  image: assets/splash.png
  fullscreen: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

scripts:
  build:
    ios: flutter build ipa -t lib/main_production.dart --flavor production && open build/ios/ipa/
    android: flutter build appbundle -t lib/main_production.dart --flavor production && open build/app/outputs/bundle/productionRelease/
  auto_route: flutter packages pub run build_runner build
  run_flutter:
    prod: flutter run --flavor production --target lib/main_production.dart
